manifest = {
 "gurmeet-ram-rahim-singh": "Saint Gurmeet Ram Rahim Singh Ji Insan (cropped).jpg",
 "asaram": "Asharam ji Bapu (cropped).jpg",
 "rampal": "Spiritual Leader Jagatguru Saint Rampal Ji Maharaj.jpg",
 "nithyananda": "Paramahamsa Nithyananda.jpg",
 "ram-janmabhoomi-teerth-kshetra-trust": "Ram Janmbhoomi Mandir, Ayodhya Dham.jpg",
 "travancore-devaswom-board": "Sabarimala 4.jpg",
 "tirumala-tirupati-devasthanams": "Tirumala Venkateswara temple entrance 09062015.JPG",
 "baba-ramdev": "Baba Ramdev.jpg",
 "jaggi-vasudev": "Sadhguru-Jaggi-Vasudev.jpg",
 "sri-sri-ravi-shankar": "Sri Sri Ravi Shankar in 2026.jpg",
 "sathya-sai-baba": "Sri Sathya Sai Baba at Brindavan.jpg",
 "sathya-sai-central-trust": "Prasanthi Nilayam - Sri Sathya Sai Baba 01.jpg",
 "shri-saibaba-sansthan-trust": "Shirdi Sai Baba Samadhi.jpg",
 "madhusudan-sai": "Sri Madhusudan Sai.jpg",
 "dhirendra-krishna-shastri": "Dhirendra Krishna Shastri.jpg",
 "premanand-maharaj": "Mahamandleshwar Swami Premanand Ji Maharaj.JPG",
 "paramahamsa-vishwananda": "Paramahamsa Vishwananda.jpg",
 "mata-amritanandamayi": "Mata Amritanandamayi.jpg",
 "gurinder-singh-dhillon": "Baba Gurinder Singh 8x10.jpg",
 "baps-robbinsville": "BAPS Robbinsville Mandir - Exterior.jpg",
 "rajneesh-osho": "Osho Rajneesh.jpg",
 "bikram-choudhury": "Bikram Choudhury.jpg",
 "iskcon-child-abuse-litigation": "Iskcon temple, Juhu, Mumbai.JPG",
 "daati-maharaj": "Paramhans Daati Ji Maharaj .jpg",
 "kalki-bhagwan": "Kalkibhagwanvijaykumarnaidu.jpg",
 "premananda-tiruchi": "Samadhi Temple.jpg",
 "jayendra-saraswathi": "Jayendra Saraswathi.jpg",
}
skipped = [
 "narayan-sai", "bajinder-singh", "surajpal-bhole-baba", "aniruddhacharya",
 "virender-dev-dixit", "radhe-maa", "nirmal-baba", "chandraswami",
 "sarathi-baba", "shiva-shankar-baba", "amarpuri-jalebi-baba", "swami-chinmayanand",
]
