// Bakes markdown documents into a TS module so pages never read the filesystem at request time
// (needed for Cloudflare Workers, where there is no fs).
import fs from "node:fs";
const en = fs.readFileSync("EDITORIAL_POLICY.md", "utf8");
const hi = fs.existsSync("EDITORIAL_POLICY.hi.md") ? fs.readFileSync("EDITORIAL_POLICY.hi.md", "utf8") : null;
fs.mkdirSync("src/generated", { recursive: true });
fs.writeFileSync("src/generated/policy.ts",
  `// generated by scripts/prebuild.ts — do not edit\nexport const POLICY_EN = ${JSON.stringify(en)};\nexport const POLICY_HI: string | null = ${JSON.stringify(hi)};\n`);
console.log("generated src/generated/policy.ts");
